version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: xmabjBjdhdsib2ubyGHbnbc7v1yt7
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/outsinya
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle:
    driver: local
